plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def keystoreProps = new Properties()
def keystoreFile = rootProject.file("local.properties")
if (keystoreFile.exists()) keystoreProps.load(new FileInputStream(keystoreFile))

android {
    namespace 'eu.myra.myraai'
    compileSdk 35

    defaultConfig {
        applicationId "eu.myra.myraai"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "1.0.3"
    }

    signingConfigs {
        release {
            storeFile     file(keystoreProps['RELEASE_STORE_FILE'] ?: '/dev/null')
            storePassword keystoreProps['RELEASE_STORE_PASSWORD'] ?: ''
            keyAlias      keystoreProps['RELEASE_KEY_ALIAS']      ?: ''
            keyPassword   keystoreProps['RELEASE_KEY_PASSWORD']   ?: ''
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    bundle {
        language {
            enableSplit = false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
}
